 class raghav
  {
     public Double a=1.0,b=1.0,c=1.0;
     public int d=1;
      double rag( )
      {
                if(d==1)
                    { a=b+a; }
                     if(d==2)
                { a=a-b;}
                 if(d==3)
                    {   a=a*b;}
                 if(d==4)
                    {    a=a/b;}    
                 if(d==5)
                {
                     for(;b>=1;b--)
                     {c=c*a;}    
                    a=c;
                }
                 if(d==0)
                 { }
                 return a;
      }
   }
public class NewJFrame2 extends javax.swing.JFrame {
Double f,g,h;
int  op; 
boolean raghav=true,operrand=true,on=true; 
raghav r1=new raghav();
/**
     * Creates new form NewJFrame2
     */int a,b,x;
    public NewJFrame2() {
        initComponents();
    a=1;x=1;}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("7");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("8");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("9");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("4");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("5");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("6");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("1");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("2");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("3");
        jButton9.setEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        t1.setEnabled(false);
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("ON");
        jToggleButton1.setToolTipText("");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton10.setText("0");
        jButton10.setEnabled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText(".");
        jButton11.setEnabled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("=");
        jButton12.setEnabled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("<-");
        jButton13.setEnabled(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("+");
        jButton14.setEnabled(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("-");
        jButton15.setEnabled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("*");
        jButton16.setEnabled(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("/");
        jButton17.setEnabled(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("1/x");
        jButton18.setEnabled(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("+\\-");
        jButton19.setEnabled(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setText("CLEAR");
        jButton20.setEnabled(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setText("[ ]^0.5");
        jButton21.setEnabled(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setText("x^y");
        jButton22.setEnabled(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton24.setText("x^2");
        jButton24.setEnabled(false);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton25.setText("x^3");
        jButton25.setEnabled(false);
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton25))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton22)
                                            .addComponent(jButton16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton17)
                                            .addComponent(jButton19)))
                                    .addComponent(jButton21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton18)
                                    .addComponent(jButton20)
                                    .addComponent(jButton15)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton6)))
                    .addComponent(jToggleButton1))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton17)
                    .addComponent(jButton16)
                    .addComponent(jButton15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton19)
                    .addComponent(jButton20)
                    .addComponent(jButton22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(jButton24)
                    .addComponent(jButton25)
                    .addComponent(jButton18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton13)
                    .addComponent(jButton14)
                    .addComponent(jButton21))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
            if(a==0)
            {t1.setText(t1.getText()+jButton1.getText()); }
            else
    { t1.setText(jButton1.getText());this.a=0;}// TODO add your handling code here:
    }                                        

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
       if(on) 
       { t1.setText("0");
        jButton1.setEnabled(true);jButton3.setEnabled(true);jButton4.setEnabled(true);
        jButton5.setEnabled(true);jButton2.setEnabled(true);jButton6.setEnabled(true);
        jButton9.setEnabled(true);jButton8.setEnabled(true);jButton7.setEnabled(true);
        jButton10.setEnabled(true);jButton13.setEnabled(true);jButton18.setEnabled(true);
        jButton11.setEnabled(true);jButton15.setEnabled(true);jButton14.setEnabled(true);
        jButton12.setEnabled(true);jButton16.setEnabled(true);jButton17.setEnabled(true);
        jButton19.setEnabled(true);jButton20.setEnabled(true);jButton21.setEnabled(true);this.b=1;
        jButton22.setEnabled(true);t1.setEnabled(true);this.a=1;this.g=1.0;this.h=1.0;this.f=1.0;
        this.on=false; jButton25.setEnabled(true);jButton24.setEnabled(true);
       }
        else
       {   t1.setText(null);
        jButton1.setEnabled(false);jButton3.setEnabled(false);jButton4.setEnabled(false);
        jButton5.setEnabled(false);jButton2.setEnabled(false);jButton6.setEnabled(false);
        jButton9.setEnabled(false);jButton8.setEnabled(false);jButton7.setEnabled(false);
        jButton10.setEnabled(false);jButton13.setEnabled(false);jButton18.setEnabled(false);
        jButton11.setEnabled(false);jButton15.setEnabled(false);jButton14.setEnabled(false);
        jButton12.setEnabled(false);jButton16.setEnabled(false);jButton17.setEnabled(false);
        jButton19.setEnabled(false);jButton20.setEnabled(false);jButton21.setEnabled(false);this.b=0;
        jButton22.setEnabled(false);t1.setEnabled(false);this.a=0;this.g=0.0;this.h=0.0;this.f=0.0;
        this.on=true;this.op=0;jButton25.setEnabled(false);
        jButton24.setEnabled(false);
       }
    }                                              

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    if(a==0)
    {t1.setText(t1.getText()+jButton8.getText());}
    else
    { t1.setText(jButton8.getText());this.a=0;}
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
if(a==0)
{ t1.setText(t1.getText()+jButton7.getText());}
else
{
t1.setText(jButton7.getText());this.a=0;
}
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    if(a==0)
    {t1.setText(t1.getText()+jButton9.getText());  }
    else
    { t1.setText(jButton9.getText());this.a=0;}
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(a==0)
        {t1.setText(t1.getText()+jButton6.getText());}
        else
    { t1.setText(jButton6.getText());this.a=0;}// TODO add your handling code here:
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(a==0)
                {t1.setText(t1.getText()+jButton5.getText());} 
        else
    { t1.setText(jButton5.getText());this.a=0;}// TODO add your handling code here:
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
if(a==0)
{ t1.setText(t1.getText()+jButton4.getText()); }
else
    { t1.setText(jButton4.getText());this.a=0;}// TODO add your handling code here:
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(a==0)
        {t1.setText(t1.getText()+jButton2.getText());   }  
        else
    { t1.setText(jButton2.getText());this.a=0;}// TODO add your handling code here:
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(a==0)
        {t1.setText(t1.getText()+jButton3.getText());}
        else
    { t1.setText(jButton3.getText());this.a=0;}// TODO add your handling code here:
    }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if(a==0)
        {t1.setText(t1.getText()+jButton10.getText());   }
        else
    { t1.setText(jButton10.getText());this.a=0;}// TODO add your handling code here:
    }                                         

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
String s= t1.getText();
if(s.contains("."))
{
  t1.setText(s);
}
else
{    t1.setText(t1.getText()+'.');       } // TODO add your handling code here:
    }                                         

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
String p=t1.getText();
   int j;
    j=p.length();
     p= p.substring(0, j-1);
 t1.setText(p);
    }                                         

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {                                          
Double p=Double.parseDouble(t1.getText());
p=-p; 
t1.setText(Double.toString(p));// TODO add your handling code here:
// TODO add your handling code here:
    }                                         

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        Double p=Double.parseDouble(t1.getText());
        p=1/p;
        t1.setText(Double.toString(p));

    }                                         

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        t1.setText(null);  this.b=1;  this.g=this.h;  // TODO add your handling code here:
    }                                         

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {                                          
          Double p=Double.parseDouble(t1.getText());
          p=Math.sqrt(p);
         t1.setText(Double.toString(p));
        // TODO add your handling code here:
    }                                         

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
if(raghav)
{ this.g=Double.parseDouble(t1.getText());
 raghav=false;t1.setText(null);operrand=true;op=1;
}    
else
    { 
        this.h=Double.parseDouble(t1.getText());op=1;
               r1.a=g;r1.b=h;r1.d=op;g=r1.rag();  t1.setText(g.toString());
    }t1.setText(null);
    }                                         

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {                                          
if(raghav)
{ this.g=Double.parseDouble(t1.getText());
 raghav=false;t1.setText(null);this.op=2;operrand=true;r1.d=op;
}    
else
    { 
        this.h=Double.parseDouble(t1.getText());op=2;
      r1.a=g;r1.b=h;r1.d=op;g=r1.rag();           t1.setText(g.toString());
    }
        t1.setText(null);// TODO add your handling code here:
    }                                         

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {                                          
if(raghav)
{ this.g=Double.parseDouble(t1.getText());
 raghav=false;this.op=3;t1.setText(null);operrand=true;r1.d=op;
}    
else
    { //t1.setText(null);
        this.h=Double.parseDouble(t1.getText());this.op=3;
      r1.a=g;r1.b=h;r1.d=op;g=r1.rag();           t1.setText(g.toString());
    }t1.setText(null);
        // TODO add your handling code here:
    }                                         

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {                                          
if(raghav)
{ this.g=Double.parseDouble(t1.getText());t1.setText(null);
 raghav=false;op=4;operrand=true;operrand=true;r1.d=op;
}    
else
    { 
	 this.h=Double.parseDouble(t1.getText());this.op=4;
      r1.a=g;r1.b=h;r1.d=op;g=r1.rag();           t1.setText(g.toString());

    }t1.setText(null);
        // TODO add your handling code here:
    }                                         
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
     //t1.setText(null);
     if(b==1)
     { if(operrand)
        {this.h=Double.parseDouble(t1.getText());
                 r1.a=g;r1.b=h;r1.d=op;g=r1.rag();
                 t1.setText(g.toString());operrand=false;
        }
        else
         {   this.g=Double.parseDouble(t1.getText());
            r1.a=g;r1.b=h;r1.d=op;g=r1.rag();
            t1.setText(g.toString());
         }
       
     }
     else
     {
            r1.a=g;r1.b=h;r1.d=op;g=r1.rag();
            t1.setText(g.toString());
            this.b=1;
     }
    }                                         

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       this.f=Double.parseDouble(t1.getText());
       t1.setText(null);
       this.op=5;operrand=true;
       r1.a=f;r1.b=h;r1.d=op;g=f;
    }                                         

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        f=Double.parseDouble(t1.getText());f=f*f;
        t1.setText(f.toString());
    }                                         

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       f=Double.parseDouble(t1.getText());f=f*f*f;
        t1.setText(f.toString());
    }                                         

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
   

           java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2().setVisible(true);
            }
        });
    }
                        
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField t1;                  
}
