#include<iostream.h>
#include<conio.h>
void main()
{ int a,b,c,d;
   cout<<"press 1 for driver age is above and equal :25 and car manufactured in india";
   cout<<"press 2 for driver age is above and equal :25 and car not manufactured in india";
   cout<<"press 3 for driver age is below :25 and car manufactured in india";
   cout<<"press 4 for driver age is below  :25 and car not manufactured in india";
   cin>>a;
   cout<<"enter 1 for accident record is good";
   cout<<"enter 2 for accident record is not good";
   cin>>b;
   if(a==1)
   {
   }
}
